### ISSUE TITLE
在RecyclerView中下拉刷新会报错

### ISSUE THREAD

**Issue by YueSeSuiFeng** [wenchaosong/Banner#20]
在RecyclerView中下拉刷新会报错
错误如下：
 java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1000, found: 0 Pager id: cn.zhouheiya.app:id/bannerViewPager Pager class: class com.ms.banner.view.BannerViewPager Problematic adapter: class com.ms.banner.Banner$BannerPagerAdapter
     at android.support.v4.view.ViewPager.populate(ViewPager.java:1135)
     at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
     at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
     at android.view.Choreographer.doCallbacks(Choreographer.java:877)
     at android.view.Choreographer.doFrame(Choreographer.java:805)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
     at android.os.Handler.handleCallback(Handler.java:873)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:201)
     at android.app.ActivityThread.main(ActivityThread.java:6806)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:522)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

我是这样使用的
![image](https://user-images.githubusercontent.com/26158197/49693225-f5fe6400-fba7-11e8-8074-6aafd875a2ab.png)
![image](https://user-images.githubusercontent.com/26158197/49693233-1fb78b00-fba8-11e8-965c-a6b46c3c11bb.png)

求指教啊  大佬

**Comment by wenchaosong** [comment]
@YueSeSuiFeng  在 setdata 方法里面，应该调用 update 方法，刷新之后要么重新初始化 banner，要么 update，否则就会报这个错误，这是使用问题
