### ISSUE TITLE
有时候会发生java.lang.ArithmeticException: divide by zero 	

### ISSUE THREAD

**Issue by ZTFtrue** [wenchaosong/Banner#61]
```java
   private int toRealPosition(int position) {
        int realPosition;
        if (this.isLoop) {
            realPosition = (position - 1 + this.count) % this.count;
        } else {
            realPosition = (position + this.count) % this.count;
        }

        if (realPosition < 0) {
            realPosition += this.count;
        }

        return realPosition;
    }
```
```
Error detail
java.lang.ArithmeticException: divide by zero
	at com.ms.banner.Banner.toRealPosition(Banner.java:2)
	at com.ms.banner.Banner.access$1100(Banner.java:1)
	at com.ms.banner.Banner$BannerPagerAdapter$1.onClick(Banner.java:1)
	at android.view.View.performClick(View.java:6663)
	at android.view.View.performClickInternal(View.java:6635)
	at android.view.View.access$3100(View.java:794)
	at android.view.View$PerformClick.run(View.java:26199)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7593)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

**Comment by wenchaosong** [comment]
@ZTFtrue  好

**Comment by wenchaosong** [comment]
@ZTFtrue  已优化
