### ISSUE TITLE
导入到项目之后运行报错

### ISSUE THREAD

**Issue by SuperZiLu** [wenchaosong/Banner#67]
Caused by: android.view.InflateException: Binary XML file line #67: Binary XML file line #186: Error inflating class com.ms.banner.Banner

**Comment by SuperZiLu** [comment]
implementation 'com.ms:Banner:2.3.16'
implementation 'com.ms:Banner-androidx:2.3.16'
这两句依赖都要写吗？关键我要是加上有androidX的这句编译又会报错，简直是死循环。

**Comment by wenchaosong** [comment]
@SuperZiLu   你先 按照 #37 说的办法试试

**Comment by SuperZiLu** [comment]
@wenchaosong 我新建了一个项目 发现没有问题 可以正常运行。两个项目的区别 一个是把控件写在activity，报错的项目是写在fragment里面，但是就是不知道具体问题在哪 。
     Caused by: android.view.InflateException: Binary XML file line #67: Binary XML file line #25: Error inflating class com.ms.banner.Banner
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.smarteye.smarteyeForCar.base.BaseFragment.onCreateView(BaseFragment.kt:22)

**Comment by SuperZiLu** [comment]
最终我换了个轮播控件 这个问题就没有了 搞了整整两天 啊啊啊啊啊啊啊啊
