### ISSUE TITLE
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter

### ISSUE THREAD

**Issue by bakonMa** [wenchaosong/Banner#86]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 5000, found: 1 Pager id: com.lhp.lo:id/bannerViewPager Pager class: class com.ms.banner.view.BannerViewPager Problematic adapter: class com.ms.banner.Banner$BannerPagerAdapter
at android.support.v4.view.ViewPager.populate(Unknown Source:617)
at android.support.v4.view.ViewPager.populate(Unknown Source:2)
at android.support.v4.view.ViewPager.setOffscreenPageLimit(Unknown Source:40)
at com.ms.banner.Banner.setOffscreenPageLimit(Unknown Source:4)
at com.ms.banner.Banner.update(Unknown Source:56)

这是调用的地方，之前有缓存，比如是2条，刷新后新数据是1条
//banner 刷新
bannerList.clear();
bannerList.addAll(homeNewDetailData.banner_list);
banner.update(bannerList);

5000 是设置的最大值吗？

**Comment by bakonMa** [comment]
只有原来是2条，变成1条的时候才会重现

**Comment by wenchaosong** [comment]
@bakonMa  感谢发现的问题，已修复，可以使用最新版本

**Comment by bakonMa** [comment]
👍  我抽空测试一下
